### ISSUE TITLE
events.py fails  - AttributeError: 'WeConnect' object has no attribute '_WeConnect__api'. 

### ISSUE THREAD

**Issue by luto65** [daernsinstantfortress/WeConnect-Cupra-python#10]
Hi, related with another issue, when using events.py

#  Initialize WeConnect
Traceback (most recent call last):
  File "/Users/####/WeConnect-Cupra-python/examples/events.py", line 48, in <module>
    main()
  File "/Users/####/WeConnect-Cupra-python/examples/events.py", line 18, in main
    weConnect = weconnect_cupra.WeConnect(username=args.username, password=args.password, updateAfterLogin=False, loginOnInit=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/####/miniconda3/lib/python3.11/site-packages/weconnect_cupra/weconnect_cupra.py", line 97, in __init__
    self.__fetcher.base_url = self.__api.base_url
                              ^^^^^^^^^^
AttributeError: 'WeConnect' object has no attribute '_WeConnect__api'. Did you mean: '_WeConnect__elapsed'?

**Comment by daernsinstantfortress** [comment]
Honestly, those examples are in a bit of a mess and probably don't work very well at all, so this doesn't surprise me and it's not very high on my list to fix either, I'm afraid.

Try access_status.py - this probably works ok.
