### ISSUE TITLE
Randomly for few days or longer I cant use this API anymore

### ISSUE THREAD

**Issue by FurkanVG** [daernsinstantfortress/WeConnect-Cupra-python#20]
I run into this error:

```
PS C:\Scripts\Cupra\Furkans-Cupra-Born> & python $pythonScriptFile -u $username -p $password --service $service
#  Initialize WeConnect
#  Login
Traceback (most recent call last):
  File "C:\Scripts\Cupra\Furkans-Cupra-Born\Cupra-FetchVehicleInfos.py", line 39, in <module>
    main()
  File "C:\Scripts\Cupra\Furkans-Cupra-Born\Cupra-FetchVehicleInfos.py", line 29, in main
    weConnect.login()
  File "C:\Users\Furkan\AppData\Local\Programs\Python\Python312\Lib\site-packages\weconnect_cupra\weconnect_cupra.py", line 166, in login
    self.__session.login()
  File "C:\Users\Furkan\AppData\Local\Programs\Python\Python312\Lib\site-packages\weconnect_cupra\api\cupra\auth\my_cupra_session.py", line 47, in login
    response = self.doWebAuth(authorizationUrl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Furkan\AppData\Local\Programs\Python\Python312\Lib\site-packages\weconnect_cupra\api\cupra\auth\my_cupra_session.py", line 191, in doWebAuth
    raise APICompatibilityError('No user id provided')
```

Did something change?!

**Comment by daernsinstantfortress** [comment]
Yes, Cupra added a load of new consents that need to be accepted. See here:

https://github.com/daernsinstantfortress/cupra_we_connect/issues/62

Long and short of it, log off the official app, log back in and you'll get a whole load of consents. Accept them all and it should start working again.

**Comment by FurkanVG** [comment]
Hey @daernsinstantfortress, thanks for this!

This somehow fixed it on my Windows OS, but not in my Linux OS for some reason... I  get this in my linux enviroment:

```
/home/furkan/.local/lib/python3.11/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "/home/furkan/Scripts/Furkans-Cupra-Born/Cupra-FetchVehicleInfos.py", line 39, in <module>
    main()
  File "/home/furkan/Scripts/Furkans-Cupra-Born/Cupra-FetchVehicleInfos.py", line 31, in main
    weConnect.update()
  File "/home/furkan/.local/lib/python3.11/site-packages/weconnect_cupra/weconnect_cupra.py", line 176, in update
    self.__api.update(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/furkan/.local/lib/python3.11/site-packages/weconnect_cupra/api/cupra/api.py", line 39, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/furkan/.local/lib/python3.11/site-packages/weconnect_cupra/api/cupra/api.py", line 45, in updateVehicles
    data = self.__fetcher.fetchData(url, force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/furkan/.local/lib/python3.11/site-packages/weconnect_cupra/fetch.py", line 74, in fetchData
    raise RetrievalError(f'Could not fetch data. Status Code was: {statusResponse.status_code}')
weconnect_cupra.errors.RetrievalError: Could not fetch data. Status Code was: 404
#  Initialize WeConnect
#  Login
#  update
```
Still trying to figure out why, but i dont think its related to this issue anymore!

**Comment by FurkanVG** [comment]
After reinstalling/updating my modules, it got fixed. Thanks! Issue closed.
